In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.12/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [2]:
tf.__version__

'2.20.0'

In [3]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [4]:
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [5]:
y = tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [6]:
z= tf.constant("India")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [7]:
s = tf.constant([1,2,3,4,5,6])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [8]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [9]:
t_2d=tf.constant([[1,2],[3,4]])
t_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [10]:
t_1d=tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [11]:
t_2d_1=tf.constant([1,2,3,4],shape=(2,2),dtype="int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [12]:
t_3d_1=tf.constant([[[1,2],[2,3],[3,4]]],dtype="float32")
t_3d_1

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]]], dtype=float32)>

In [13]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [14]:
t_3d_1.shape

TensorShape([1, 3, 2])

# Tensorflow Variable


In [15]:
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [16]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [17]:
x.name

'Variable:0'

In [18]:
x.shape

TensorShape([4])

In [19]:
x.dtype

tf.int32

In [20]:
y=tf.Variable([1.0,2,3.3,4])
y

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1. , 2. , 3.3, 4. ], dtype=float32)>

In [21]:
z=tf.Variable(True,False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [22]:
t_con=tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [23]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [24]:
t_2d=tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [25]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [26]:
tf.reshape(x,(2,2))
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [27]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

##Convert as Tensor

In [28]:
tf.convert_to_tensor(x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [29]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

##Assigning new value to Tensor

In [30]:
x=tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [31]:
x.assign([4,6,2,8])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [32]:
x.assign([4,6,2,9])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

##Assigning addition variable with another memory

In [33]:
x.assign_add([4,6,2,8])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

##Math Modules In Tensorflow

In [34]:
import numpy as np

In [35]:
a=10
b=20
a+b

30

In [36]:
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [37]:
#Addition of Two List

l1=[1,2,3,4]
l2=[5,6,7,8]
tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [38]:
# Addition of Two tuple
t1=(2,3,4,5)
t2=(5,6,7,8)
tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 7,  9, 11, 13], dtype=int32)>

In [39]:
l1=[1,2,3,4]
a=10
tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [40]:
# Given a tensor x and a tensor y, this operation x^y computes for corresponding elements in x and y

x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [41]:
# real number
x = tf.constant([-2.25, 3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [42]:
# complex number
x = tf.constant([[-2.25 + 4.75j], [-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [43]:


x = [1, 2, 3, 4, 5]
y = 1
tf.subtract(x, y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [44]:
x = [1, 2, 3, 4, 5]
y = 1
tf.subtract(y, x)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 0, -1, -2, -3, -4], dtype=int32)>

In [45]:
import tensorflow as tf
x = tf.constant(([1, 2, 3, 4]))
tf.math.multiply(x, x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [46]:
tf.multiply(x, x)
tf.math.multiply(7,6)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [47]:
x = tf.ones([1, 2]);
y = tf.ones([2, 1]);
x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [48]:
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2., 0., 2., 5.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [49]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [50]:

x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [51]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.minimum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [52]:
x = tf.constant([0, 0.5, 1, 5])
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [53]:
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [54]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [55]:
x = tf.constant([[4.0], [16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [56]:
y = tf.constant([[-4.0], [16.0]])
tf.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [57]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [58]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [59]:
ones_2d= tf.ones((2,2)),tf.float32
ones_2d

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [60]:
ones_3d=tf.ones((2,2,4),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [61]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [62]:
zeros_2d=tf.zeros((2,2),dtype=tf.int32)
zeros_2d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [63]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [64]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## **Placeholder**-Migrate tensorflow 1 code to tensorflow 2
Place holder is a variable that we will assign data to at a later date.

In [67]:
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

x = tf.placeholder(tf.float32, shape=(400, 400))

print(x)

Instructions for updating:
non-resource variables are not supported in the long term


Tensor("Placeholder:0", shape=(400, 400), dtype=float32)


In [68]:
tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [69]:
tf.compat.v1.disable_eager_execution()

In [70]:
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
a

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [71]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_3:0' shape=(400, 400) dtype=float32>

In [72]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [73]:
ones_array=np.ones((400,400),np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [74]:
with tf.compat.v1.Session() as sess:
   d=sess.run(c,feed_dict={a:ones_array,b:ones_array})
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

## **Sparse Tensors**
It enables efficient storage & processing of tensors that contains lot of zero values

In [78]:
import tensorflow as tf

sparse_tensor = tf.SparseTensor(
    indices=[[0, 1], [1, 2]],   # positions
    values=[10, 20],            # values at those positions
    dense_shape=[3, 4]          # total shape
)

print(sparse_tensor)

SparseTensor(indices=Tensor("SparseTensor_2/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_2/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_2/dense_shape:0", shape=(2,), dtype=int64))


In [76]:
tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [77]:
st1=tf.SparseTensor(indices=[[0,3],[2,4]],values=[10,20],dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [79]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


In [80]:
import tensorflow as tf
x = tf.compat.v1.get_variable("x", dtype=tf.int32,  initializer=tf.constant([5]))
y = tf.compat.v1.get_variable("y", dtype=tf.int32,  initializer=tf.constant([6]))

In [81]:
c = tf.constant([5], name ="constant")
square = tf.constant([2], name ="square")
f = tf.multiply(x, y) + tf.pow(x, square) + y + c
f


<tf.Tensor 'add_3:0' shape=(1,) dtype=int32>