# Tensors in Python

In [4]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


#Creating a Tensor in Pytorch

In [ ]:
# using empty
a = torch.empty(2,3)
a

tensor([[ 1.6330e-38,  0.0000e+00,  1.6393e-38],
        [ 0.0000e+00, -5.0604e-20,  4.3189e-41]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.2572, 0.1259, 0.8617],
        [0.5924, 0.5343, 0.3377]])

In [ ]:
#Manual Seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(500)
torch.rand(4,5)

tensor([[0.5820, 0.1338, 0.7995, 0.3071, 0.6526],
        [0.6105, 0.1575, 0.6983, 0.7883, 0.7981],
        [0.4593, 0.8997, 0.2518, 0.5648, 0.0302],
        [0.5930, 0.6386, 0.4795, 0.6030, 0.7351]])

In [ ]:
#Using Tensors
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,7))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [ ]:
x = torch.tensor([[7,2,3],[4,5,6]])
x

tensor([[7, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[       1144719728,        1123840624, 72340172838076673],
        [                1,                96,                80]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7602, 0.8872, 0.8153],
        [0.2794, 0.0168, 0.6273]])

#Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
# assign datatype
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[7., 2., 3.],
        [4., 5., 6.]])

 # Mathematical operations

In [ ]:
# Scalar Operation
x = torch.rand(2,2)
x


tensor([[0.6037, 0.1817],
        [0.3849, 0.8164]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.3644, 0.0330],
        [0.1482, 0.6665]])

# 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3086, 0.4626, 0.7494],
        [0.9410, 0.0619, 0.6229]])
tensor([[0.8790, 0.6113, 0.6402],
        [0.0360, 0.4153, 0.2534]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3086, 0.4626, 0.1091],
        [0.0048, 0.0619, 0.1161]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

# 3. Reduction operation

In [7]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[7., 2., 0.],
        [7., 4., 9.]])

In [8]:
torch.sum(e, dim=0)

tensor([14.,  6.,  9.])

In [9]:
torch.sum(e)

tensor(29.)

In [10]:
# Mean
torch.sum(e)
#mean along col
torch.mean(e, dim=0)
#mean along row
torch.mean(e, dim=1)

tensor([3.0000, 6.6667])

In [11]:
# median
torch.median(e)

tensor(4.)

In [12]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [13]:
# product
torch.prod(e)

tensor(0.)

In [14]:
# standard deviation
torch.std(e)

tensor(3.4303)

In [15]:
# variance
torch.var(e)

tensor(11.7667)

In [16]:
# argmax
torch.argmax(e)

tensor(5)

In [17]:
# argmin
torch.argmin(e)

tensor(2)

# 4. Matrix operations

In [18]:
a = torch.randint(size=(2,3), low=0, high=10)
c= torch.randint(size=(3,2), low=0, high=10)

print(a)
print(c)

tensor([[7, 9, 5],
        [8, 4, 2]])
tensor([[7, 8],
        [5, 0],
        [6, 4]])


In [19]:
# matrix multiplcation
torch.matmul(a, c)

tensor([[124,  76],
        [ 88,  72]])

In [20]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [22]:
# transpose
torch.transpose(a, 0, 1)

tensor([[7, 8],
        [9, 4],
        [5, 2]])

In [23]:
b = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
b

tensor([[2., 8., 7.],
        [8., 6., 3.],
        [8., 3., 2.]])

In [25]:
# determinant
torch.det(b)

tensor(-98.)

In [28]:
# inverse
torch.inverse(b)

tensor([[-0.0306, -0.0510,  0.1837],
        [-0.0816,  0.5306, -0.5102],
        [ 0.2449, -0.5918,  0.5306]])

# 5. Comparison operations

In [29]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[1, 6, 3],
        [8, 9, 0]])
tensor([[6, 6, 9],
        [4, 8, 5]])


In [30]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater that equal to
i>=j
# less than equal to
i<=j

tensor([[ True,  True,  True],
        [False, False,  True]])

# 6. Special functions

In [31]:
h = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 5., 7.],
        [9., 4., 9.]])

In [33]:
# log
torch.log(h)

tensor([[1.3863, 1.6094, 1.9459],
        [2.1972, 1.3863, 2.1972]])

In [34]:
# exp
torch.exp(h)

tensor([[  54.5981,  148.4132, 1096.6332],
        [8103.0840,   54.5981, 8103.0840]])

In [35]:
# sqrt
torch.sqrt(h)

tensor([[2.0000, 2.2361, 2.6458],
        [3.0000, 2.0000, 3.0000]])

In [36]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(h)

tensor([[0.9820, 0.9933, 0.9991],
        [0.9999, 0.9820, 0.9999]])

In [37]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(h, dim=0)

tensor([[0.0067, 0.7311, 0.1192],
        [0.9933, 0.2689, 0.8808]])

# Inplace Operations

In [38]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8489, 0.2703, 0.8051],
        [0.4069, 0.4186, 0.8675]])
tensor([[0.0973, 0.5240, 0.5918],
        [0.8221, 0.0563, 0.7429]])


In [39]:
m.add_(n)

tensor([[0.9462, 0.7943, 1.3969],
        [1.2289, 0.4749, 1.6105]])

In [40]:
m

tensor([[0.9462, 0.7943, 1.3969],
        [1.2289, 0.4749, 1.6105]])

In [41]:
n

tensor([[0.0973, 0.5240, 0.5918],
        [0.8221, 0.0563, 0.7429]])

In [42]:
torch.relu(m)

tensor([[0.9462, 0.7943, 1.3969],
        [1.2289, 0.4749, 1.6105]])

In [43]:
m.relu_()

tensor([[0.9462, 0.7943, 1.3969],
        [1.2289, 0.4749, 1.6105]])

In [44]:
m

tensor([[0.9462, 0.7943, 1.3969],
        [1.2289, 0.4749, 1.6105]])

# Copying a Tensor

In [45]:
a = torch.rand(2,3)
a

tensor([[0.2010, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [46]:
b = a

In [47]:
b

tensor([[0.2010, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [48]:
a[0][0] = 0

In [49]:
a

tensor([[0.0000, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [50]:
b

tensor([[0.0000, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [51]:
id(a)

137702199390880

In [52]:
id(b)

137702199390880

In [53]:
b = a.clone()

In [54]:
a

tensor([[0.0000, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [55]:
b

tensor([[0.0000, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [56]:
a[0][0] = 10

In [57]:
a

tensor([[10.0000,  0.1329,  0.5404],
        [ 0.1555,  0.8865,  0.2775]])

In [58]:
b

tensor([[0.0000, 0.1329, 0.5404],
        [0.1555, 0.8865, 0.2775]])

In [59]:
id(a)

137702199390880

In [60]:
id(b)

137702199511392

In [61]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [62]:
a.shape

torch.Size([3, 3])

In [63]:
b = torch.empty_like(a)
b

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]])